### PR TITLE
Add config for listening on a different interface.

### PR DESCRIPTION
**Pull request by pvdvreede**
As per suggestion on issue #11.

Let me know if this looks right.

Thanks.

### CODE REVIEW

**Comment by pvdvreede** [comment]
Any idea why the test is failing for only one of the versions in the matrix?

**Comment by MSch** [comment]
Thanks for the PR!

I was thinking the failure is a flaky test, but it now happened twice. Need to investigate.

Another thing I discovered, are you sure that bypass doesn't bind on all interfaces by default? I just tried `Bypass.open`` in `iex` on OS X and got a socket bound to `*` according to Activity Monitor.

I'm now guessing: Could it be that the docker interface is being added _after_ ranch/gen_tcp has opened the listen socket? And because the listen socket is just "not" bound instead of being bound to 0.0.0.0 it doesn't extend to the new interface?

**Comment by pvdvreede** [comment]
You are right it could be that issue - the docs for ranch do seem to indicate that by default the interface is 0.0.0.0. 

With that in mind would you still want to make the default for bypass be loopback only? That seems like a good default to have so that people dont accidentally expose their server. So perhaps this PR is still valid even if it doesn't fix my particular use case...?

**Comment by alco** [comment]
I like the idea of listening on the loopback interface by default.

I'm not really sure I understand the use case described in #11. How does your test look when there are multiple containers involved? Perhaps, you just need to run a Plug server. Bypass is supposed to be used as a quick way to spin up an HTTP server inside the same process that is running your ExUnit tests. Listening on the loopback interface should be sufficient for that purpose.

**Pull request closed without merging**
