### PR TITLE
Allow redefining the expectations for a route

### LINKED ISSUE #80: Allow the redefinition of routes
Often my application needs to send multiple requests to a single route in a single test. As of this version, I need to declare a route with a `Bypass.expect/4` that matches all the requests, and this quickly becomes a bloated match. [Mox](https://github.com/plataformatec/mox) allows you to add multiple expectations, that leads to simple code. I'm not asking for expectations to be as complete as Mox, but allowing to redefine the route would be great. 

This looks like to be simple, it should be a matter of making this match

https://github.com/PSPDFKit-labs/bypass/blob/0e44e6582f1e2ec580cbc21df6d907e7df5f2a3b/lib/bypass/instance.ex#L118-L131

into

```elixir
 updated_expectations = 
       Map.put(expectations, route, new_route( 
         fun, 
         case expect do 
           :expect -> :once_or_more 
           :expect_once -> :once 
           :stub -> :none_or_more 
         end 
       ))
```

### PR DESCRIPTION
**Pull request by VitorTrin**
Closes #80

### CODE REVIEW

**Comment by yordis** [comment]
@MSch Hey there, I don't see that much activity on the repo so I thought was a good idea to ping you directly.

Is there any possibility to merge this and release it?

I am currently adding complexity because I need this feature, please help use.

**Comment by JonRowe** [comment]
If you don't want this to be the default would you consider an additional call to allow it? like `update_expect` or similar?

**Comment by ream88** [comment]
@MSch any chance this being pulled in?

**Comment by ream88** [comment]
Hey @VitorTrin thx for the update, I will merge this asap!

**Pull request merged**
