### PR TITLE
Switch from :simple_one_for_one to DynamicSupervisor

### PR DESCRIPTION
**Pull request by anthonator**

### CODE REVIEW

**Comment by anthonator** [comment]
Closes #86

**Comment by anthonator** [comment]
Anything I can do to help push this along?

**Comment by anthonator** [comment]
@MSch anything I can do to help get this merged?

**Comment by hewsut** [comment]
@MSch's last commit 2018... 🤔 

I really want to use Bypass but this warning is quite the nuance.

**Comment by ream88** [comment]
Hey Mario here, this will be merged soon: https://github.com/PSPDFKit-labs/bypass/issues/88 😊

**Comment by TheFirstAvenger** [comment]
@ream88 Can we have a 1.0.1 pushed to hex with this change?

**Comment by ream88** [comment]
As this just generates an ugly deprecation message, but merging it would break compatibility with Elixir < 1.6, I say wait for 2.0.

/cc @MSch Wait is your opinion?

**Comment by TheFirstAvenger** [comment]
What is the current eta on 2.0?

**Comment by thiamsantos** [comment]
@ream88 Those will come with version 2.0? I would like to get rid of the `compile warnings`.

**Pull request merged**
