### PR TITLE
Adds support for different plug adapters

### PR DESCRIPTION
**Pull request by hassox**
This is in response to using cowboy2 in an existing app but not having the ability to update the adapter in bypass (which we love!)

### CODE REVIEW

**Comment by AndrewDryga** [comment]
@MSch Can you please merge this and release a new version? Plug and Phoenix are on cowboy2 now and bypass doesn't work, the only way for us it to use the fork.

**Comment by MSch** [comment]
Hi @hassox, thank you so much for your great contribution!

Before I can merge this, can you please sign our CLA: Hi @IRog, thanks for your contribution.

Can you add code to monitor the process and wait for it to die, so that the code remains synchronous?

Please also sign our CLA: https://pspdfkit.com/guides/web/current/miscellaneous/contributing/

Please ping me here when you've done this, then I'll release a new version.

**Comment by tsupertramp** [comment]
Hey @hassox any update to sign the CLA? 👍 - Would love to have this merged.

**Comment by eaguilera23** [comment]
How did you made this work with the fork? It still asks me for cowboy 1. @AndrewDryga

**Comment by hassox** [comment]
@Msch sorry for the delay. Agreement is signed!

**Comment by nathany** [comment]
@hassox 

```
{:bypass, "~> 0.8.1", github: "hassox/bypass", ref: "allow-for-different-plug-adapter", only: :test},
```

**Comment by MSch** [comment]
@hassox Thank you so much! I've released 0.9.0 just now! \o/

**Pull request merged**
