### PR TITLE
Test against elixir 1.3.1 & OTP R19

### PR DESCRIPTION
**Pull request by gmile**

### CODE REVIEW

**Comment by alco** [comment]
@gmile Thanks for the PR! Let's wait for Elixir v1.3.2 which should fix the compilation issues with `cowboy` and `cowlib`, already fixed in Elixir master – [commit](https://github.com/elixir-lang/elixir/commit/65aee00809257ce73991d1b41e2c640942c86c9e).

**Comment by gmile** [comment]
> already fixed in Elixir master

Perfect, thanks! I already started thinking it would have to be cowboy / cowlib that need to be fixed

**Comment by alco** [comment]
@gmile Could you squash it please and rebase on master?

**Comment by gmile** [comment]
@alco sure, no problem

**Comment by alco** [comment]
@gmile Looks like we need to exclude Elixir v1.2.5 + Erlang 19.

**Comment by gmile** [comment]
@alco force-pushed the change skipping Elixir v1.2.5 + Erlang 19

**Pull request merged**
