### PR TITLE
Replace cowboy dependency with plug_cowboy

### PR DESCRIPTION
**Pull request by oo6**
Plug 1.7 extract `Plug.Adapters.Cowboy` and `Plug.Adapters.Cowboy2` into [plug_cowboy](https://github.com/elixir-plug/plug_cowboy).

So we can remove some configuration and use `Plug.Cowboy` directly.

### CODE REVIEW

**Comment by binarylogic** [comment]
I can confirm this resolves the issue against the current latest version of `:plug` (`1.7.0`). Could we get a merge and release? This will break backward compatibility, so I assume this would be released as `1.0.0`?

**Comment by danschultzer** [comment]
@MSch this works. Is there anything else that's needed before this can be merged in?

**Comment by jc00ke** [comment]
I can confirm that these changes work against a Phoenix 1.4 app. I just upgraded mine today and this was the only issue. Thanks @oo6!

**Comment by philipp-spiess** [comment]
@oo6 It seems that tests where not running - I've added an empty commit to your branch and now they're failing. Can you look into this? 🙂

**Comment by oo6** [comment]
@philipp-spiess Fixed.

**Pull request merged**
