### PR TITLE
on_exit should wait for a request to complete (#39)

### PR DESCRIPTION
**Pull request by paulswartz**

### CODE REVIEW

**Comment by MSch** [comment]
@paulswartz Hi Paul, is your PR still relevant given we are about to merge https://github.com/PSPDFKit-labs/bypass/pull/36 ?

**Comment by paulswartz** [comment]
It looks like that also addresses my issue.

**Comment by MSch** [comment]
We merged #41 - closing this

**Comment by MSch** [comment]
@paulswartz We just released 0.7.0.

**Pull request closed without merging**
