### PR TITLE
Make listen interface configurable

### PR DESCRIPTION
**Pull request by boris-kloeckner**
We have a special use case which requires to use bypass in a docker compose so it should be able to receive requests coming from other containers. 
This PR makes _listen_ip_ configurable and keeps loopback as a default interface.

Solving #11

### CODE REVIEW

**Comment by MSch** [comment]
@boris-kloeckner Can you rebase your PR and sign our [CLA](https://pspdfkit.com/guides/web/current/miscellaneous/contributing/)? I'll then merge and release a new version

**Comment by boris-kloeckner** [comment]
@MSch done

**Comment by yammine** [comment]
@MSch Any plans on merging this?

**Comment by ream88** [comment]
@boris-kloeckner merged! Thx a lot for your contributions! 😊

**Pull request merged**
